### ISSUE TITLE
Documents need cleanup

### ISSUE THREAD

**Issue by OverPoweredDev** [OverPoweredDev/Pharma_NLPSearch#1]
So far, the documents used in search_list_txt/ have been succesfully segregated into parts of Abstract, Introduction and all. Parts in the abstract have even been cleaned up so do the same for the other parts i.e. remove garbage text left from pdf scanning, random numbers left as aresult of converting tables to text.

_Note: Do **NOT** change the Document Sections i.e. Abstract, Keywords, Introduction, Main, Conclusion, References, Acknowledgements, End_

**Comment by Chronicle18** [comment]
Thenks
